
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://serviceBanque/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toString", targetNamespace = "http://serviceBanque/", className = "service.ToString")
    @ResponseWrapper(localName = "toStringResponse", targetNamespace = "http://serviceBanque/", className = "service.ToStringResponse")
    @Action(input = "http://serviceBanque/BanqueWS/toStringRequest", output = "http://serviceBanque/BanqueWS/toStringResponse")
    public String toString();

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroDinars", targetNamespace = "http://serviceBanque/", className = "service.ConversionEuroDinars")
    @ResponseWrapper(localName = "conversionEuroDinarsResponse", targetNamespace = "http://serviceBanque/", className = "service.ConversionEuroDinarsResponse")
    @Action(input = "http://serviceBanque/BanqueWS/conversionEuroDinarsRequest", output = "http://serviceBanque/BanqueWS/conversionEuroDinarsResponse")
    public double conversionEuroDinars(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://serviceBanque/", className = "service.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://serviceBanque/", className = "service.GetCompteResponse")
    @Action(input = "http://serviceBanque/BanqueWS/getCompteRequest", output = "http://serviceBanque/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://serviceBanque/", className = "service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://serviceBanque/", className = "service.GetComptesResponse")
    @Action(input = "http://serviceBanque/BanqueWS/getComptesRequest", output = "http://serviceBanque/BanqueWS/getComptesResponse")
    public List<Compte> getComptes();

}
